name: CI/CD

on:
  push:
    branches:
      - 'master'

jobs:
  genVer:  # Generates a semantic versioning number to apply to docker image and nodejs package
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.nextVer.outputs.version }}
      verNum: ${{ steps.nextVer.outputs.verNum  }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Get PR and Labels
        id: PR
        uses: actions-ecosystem/action-get-merged-pull-request@v1.0.1
        with:
          github_token: ${{ github.token }}

      - name: Get Previous Tag
        id: previousTag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 0.1.0
      
      - name: Generate Next Versions
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}
      
      - name: Get Next Version
        id: nextVer
        run: |
          if ${{ contains(steps.PR.outputs.labels, 'patch') }}; then
            echo "version=${{ steps.semvers.outputs.v_patch }}" >> $GITHUB_OUTPUT
            echo "verNum=${{ steps.semvers.outputs.patch }}" >> $GITHUB_OUTPUT
            echo "version=${{ steps.semvers.outputs.v_patch }}" 
          fi
          if ${{ contains(steps.PR.outputs.labels, 'minor') }}; then
            echo "version=${{ steps.semvers.outputs.v_minor }}" >> $GITHUB_OUTPUT
            echo "verNum=${{ steps.semvers.outputs.minor }}" >> $GITHUB_OUTPUT
            echo "version=${{ steps.semvers.outputs.v_minor }}"
          fi
          if ${{ contains(steps.PR.outputs.labels, 'major') }}; then
            echo "version=${{ steps.semvers.outputs.v_major }}" >> $GITHUB_OUTPUT
            echo "verNum=${{ steps.semvers.outputs.major }}" >> $GITHUB_OUTPUT
            echo "version=${{ steps.semvers.outputs.v_major }}"
          fi
 
  build:  # Builds and pushes a docker image to DockerHub
    runs-on: ubuntu-latest
    needs: genVer
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: sudowatson/portfolio:latest,sudowatson/portfolio:${{ needs.genVer.outputs.verNum }}

  tagCommit:  # Tags the last commit with the newest tag version
    runs-on: ubuntu-latest
    needs: genVer
    steps:
      - uses: actions/checkout@v3
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ needs.genVer.outputs.version }}